# name: Greetings

# on: [pull_request, issues]

# jobs:
#   greeting:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/first-interaction@v1
#       with:
#         repo-token: ${{ secrets.GITHUB_TOKEN }}
#         issue-message: 'Thank you very much for creating your first issue with @codeforcauseorg.'
#         pr-message: 'Oh! great, you had started your journey with @codeforcauseorg. Someone will get back to you to review your PR. Meanwhile please have a look at [Code for cause](''https://codeforcause.org/''). Its really awesome to find you here making your first PR with @codeforcauseorg'
